export const cities = [
    { title: 'Благоевград' },
    { title: 'Бургас' },
    { title: 'Варна' },
    { title: 'Велико Търново' },
    { title: 'Видин' },
    { title: 'Враца' },
    { title: 'Габрово' },
    { title: 'Добрич' },
    { title: 'Кърджали' },
    { title: 'Кюстендил' },
    { title: 'Ловеч' },
    { title: 'Монтана' },
    { title: 'Пазарджик' },
    { title: 'Перник' },
    { title: 'Плевен' },
    { title: 'Плoвдив' },
    { title: 'Разград' },
    { title: 'Русе' },
    { title: 'Силистра' },
    { title: 'Сливен' },
    { title: 'Смолян' },
    { title: 'София' },
    { title: 'Стара Загора' },
    { title: 'Търговище' },
    { title: 'Хасково' },
    { title: 'Шумен' },
    { title: 'Ямбол' }
];
